### ISSUE TITLE
boot animation

### ISSUE THREAD

**Issue by andrew264** [ItsAnilSingh/miui-kitkat-logan2g#1]
U are using cm bootanimation in miui ROM.

**Comment by ItsAnilSingh** [comment]
In official porting guide, there is no mention of bootanimation or replacing bootanimation.
https://github.com/MiCode/patchrom/tree/kitkat
And I think, it doesnt matter what bootanimation you are using.

**Comment by andrew264** [comment]
Ok

**Comment by andrew264** [comment]
Ok
